<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="risiko" nsURI="http://www.example.org/risiko" nsPrefix="risiko">
  <eSubpackages name="board" nsURI="http://www.example.org/risiko/board" nsPrefix="board">
    <eClassifiers xsi:type="ecore:EClass" name="Board">
      <eStructuralFeatures xsi:type="ecore:EReference" name="countries" lowerBound="2"
          upperBound="-1" eType="#//board/Country" containment="true" eKeys="#//board/Country/name"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="borders" lowerBound="1"
          upperBound="-1" eType="#//board/Border" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="continents" lowerBound="1"
          upperBound="-1" eType="#//board/Continent" containment="true" eKeys="#//board/Continent/name"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="additionalTroops" lowerBound="5"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cards" lowerBound="1"
          upperBound="-1" eType="#//board/Card" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Country">
      <eStructuralFeatures xsi:type="ecore:EReference" name="border" lowerBound="1"
          upperBound="-1" eType="#//board/Border" eOpposite="#//board/Border/country"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="continent" lowerBound="1"
          eType="#//board/Continent" eOpposite="#//board/Continent/country"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Border">
      <eStructuralFeatures xsi:type="ecore:EReference" name="country" lowerBound="2"
          upperBound="2" eType="#//board/Country" eOpposite="#//board/Country/border"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//board/BorderType" defaultValueLiteral="LAND"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BorderType">
      <eLiterals name="SEA"/>
      <eLiterals name="LAND"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Continent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="country" lowerBound="1"
          upperBound="-1" eType="#//board/Country" eOpposite="#//board/Country/continent"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="additionalTroops" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Card">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" lowerBound="1"
          eType="#//board/CardSymbol"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="country" eType="#//board/Country"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CardSymbol">
      <eLiterals name="Infanterie"/>
      <eLiterals name="Kavallerie"/>
      <eLiterals name="Artillerie"/>
      <eLiterals name="Joker"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="gamestate" nsURI="http://www.example.org/risiko/gamestate" nsPrefix="gamestate">
    <eClassifiers xsi:type="ecore:EClass" name="Player">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCountries" upperBound="-1"
          eType="#//gamestate/CountryState" eOpposite="#//gamestate/CountryState/player"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCards" upperBound="-1"
          eType="#//board/Card"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="troopsToSet" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="State">
      <eStructuralFeatures xsi:type="ecore:EReference" name="players" lowerBound="1"
          upperBound="-1" eType="#//gamestate/Player" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="countryState" lowerBound="1"
          upperBound="-1" eType="#//gamestate/CountryToCountryStateMap" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CountryState">
      <eStructuralFeatures xsi:type="ecore:EReference" name="player" lowerBound="1"
          eType="#//gamestate/Player" eOpposite="#//gamestate/Player/ownedCountries"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="country" lowerBound="1"
          eType="#//board/Country"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="troops" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CountryToCountryStateMap" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//board/Country"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//gamestate/CountryState" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="actions" nsURI="http://www.example.org/risiko/actions" nsPrefix="actions">
    <eClassifiers xsi:type="ecore:EClass" name="Atack" eSuperTypes="#//actions/Action">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="troops" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="border" lowerBound="1"
          eType="#//board/Border"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SetTroops" eSuperTypes="#//actions/Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="country" lowerBound="1"
          eType="#//board/Country"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="troops" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CoinCards" eSuperTypes="#//actions/Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cards" lowerBound="3"
          upperBound="3" eType="#//board/Card"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="player" lowerBound="1"
          eType="#//gamestate/Player"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MoveTroops" eSuperTypes="#//actions/Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
          eType="#//board/Country"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//board/Country"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="troops" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
